#!/bin/bash

set -e

chmod -R 777 /var/fibertest

echo
echo "   !!!!The services are starting!!!!!!!!Службы запускаются!!!!"
echo

systemctl enable watchdog
systemctl enable rtu
sleep 4s

systemctl start watchdog.service

while ! systemctl is-active --quiet watchdog
do
sleep 1s
done  

systemctl status watchdog.service

while ! systemctl is-active --quiet rtu
do
sleep 1s
done

systemctl status rtu.service

echo
echo "   !!!!Install completed!!!!Установка завершена!!!!"
echo
