#!/bin/bash

set -e

# если службы в данный момент работают их необходимо остановить
if systemctl is-active --quiet watchdog;
then
systemctl stop watchdog.service
sleep 3s
fi

if systemctl is-active --quiet rtu; 
then
systemctl stop rtu.service
sleep 3s
fi
