//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iit.Fibertest.RtuWpfExample.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IRtuWcfService")]
    public interface IRtuWcfService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRtuWcfService/StartMonitoring", ReplyAction="http://tempuri.org/IRtuWcfService/StartMonitoringResponse")]
        void StartMonitoring();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRtuWcfService/StartMonitoring", ReplyAction="http://tempuri.org/IRtuWcfService/StartMonitoringResponse")]
        System.Threading.Tasks.Task StartMonitoringAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRtuWcfService/StopMonitoring", ReplyAction="http://tempuri.org/IRtuWcfService/StopMonitoringResponse")]
        void StopMonitoring();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRtuWcfService/StopMonitoring", ReplyAction="http://tempuri.org/IRtuWcfService/StopMonitoringResponse")]
        System.Threading.Tasks.Task StopMonitoringAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRtuWcfServiceChannel : Iit.Fibertest.RtuWpfExample.ServiceReference1.IRtuWcfService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RtuWcfServiceClient : System.ServiceModel.ClientBase<Iit.Fibertest.RtuWpfExample.ServiceReference1.IRtuWcfService>, Iit.Fibertest.RtuWpfExample.ServiceReference1.IRtuWcfService {
        
        public RtuWcfServiceClient() {
        }
        
        public RtuWcfServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RtuWcfServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RtuWcfServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RtuWcfServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void StartMonitoring() {
            base.Channel.StartMonitoring();
        }
        
        public System.Threading.Tasks.Task StartMonitoringAsync() {
            return base.Channel.StartMonitoringAsync();
        }
        
        public void StopMonitoring() {
            base.Channel.StopMonitoring();
        }
        
        public System.Threading.Tasks.Task StopMonitoringAsync() {
            return base.Channel.StopMonitoringAsync();
        }
    }
}
