//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfIntermediary.C2DWcfServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="C2DWcfServiceReference.IWcfServiceForClient")]
    public interface IWcfServiceForClient {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfServiceForClient/RegisterClient", ReplyAction="http://tempuri.org/IWcfServiceForClient/RegisterClientResponse")]
        void RegisterClient(string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfServiceForClient/RegisterClient", ReplyAction="http://tempuri.org/IWcfServiceForClient/RegisterClientResponse")]
        System.Threading.Tasks.Task RegisterClientAsync(string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfServiceForClient/UnRegisterClient", ReplyAction="http://tempuri.org/IWcfServiceForClient/UnRegisterClientResponse")]
        void UnRegisterClient(string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfServiceForClient/UnRegisterClient", ReplyAction="http://tempuri.org/IWcfServiceForClient/UnRegisterClientResponse")]
        System.Threading.Tasks.Task UnRegisterClientAsync(string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfServiceForClient/CheckRtuConnection", ReplyAction="http://tempuri.org/IWcfServiceForClient/CheckRtuConnectionResponse")]
        bool CheckRtuConnection(Dto.CheckRtuConnectionDto rtuAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfServiceForClient/CheckRtuConnection", ReplyAction="http://tempuri.org/IWcfServiceForClient/CheckRtuConnectionResponse")]
        System.Threading.Tasks.Task<bool> CheckRtuConnectionAsync(Dto.CheckRtuConnectionDto rtuAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfServiceForClient/InitializeRtu", ReplyAction="http://tempuri.org/IWcfServiceForClient/InitializeRtuResponse")]
        bool InitializeRtu(Dto.InitializeRtuDto rtu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfServiceForClient/InitializeRtu", ReplyAction="http://tempuri.org/IWcfServiceForClient/InitializeRtuResponse")]
        System.Threading.Tasks.Task<bool> InitializeRtuAsync(Dto.InitializeRtuDto rtu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfServiceForClient/StartMonitoring", ReplyAction="http://tempuri.org/IWcfServiceForClient/StartMonitoringResponse")]
        bool StartMonitoring(string rtuAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfServiceForClient/StartMonitoring", ReplyAction="http://tempuri.org/IWcfServiceForClient/StartMonitoringResponse")]
        System.Threading.Tasks.Task<bool> StartMonitoringAsync(string rtuAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfServiceForClient/StopMonitoring", ReplyAction="http://tempuri.org/IWcfServiceForClient/StopMonitoringResponse")]
        bool StopMonitoring(string rtuAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfServiceForClient/StopMonitoring", ReplyAction="http://tempuri.org/IWcfServiceForClient/StopMonitoringResponse")]
        System.Threading.Tasks.Task<bool> StopMonitoringAsync(string rtuAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfServiceForClient/ApplyMonitoringSettings", ReplyAction="http://tempuri.org/IWcfServiceForClient/ApplyMonitoringSettingsResponse")]
        bool ApplyMonitoringSettings(Dto.ApplyMonitoringSettingsDto settings);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfServiceForClient/ApplyMonitoringSettings", ReplyAction="http://tempuri.org/IWcfServiceForClient/ApplyMonitoringSettingsResponse")]
        System.Threading.Tasks.Task<bool> ApplyMonitoringSettingsAsync(Dto.ApplyMonitoringSettingsDto settings);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfServiceForClient/AssignBaseRef", ReplyAction="http://tempuri.org/IWcfServiceForClient/AssignBaseRefResponse")]
        bool AssignBaseRef(Dto.AssignBaseRefDto baseRef);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfServiceForClient/AssignBaseRef", ReplyAction="http://tempuri.org/IWcfServiceForClient/AssignBaseRefResponse")]
        System.Threading.Tasks.Task<bool> AssignBaseRefAsync(Dto.AssignBaseRefDto baseRef);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWcfServiceForClientChannel : WcfIntermediary.C2DWcfServiceReference.IWcfServiceForClient, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WcfServiceForClientClient : System.ServiceModel.ClientBase<WcfIntermediary.C2DWcfServiceReference.IWcfServiceForClient>, WcfIntermediary.C2DWcfServiceReference.IWcfServiceForClient {
        
        public WcfServiceForClientClient() {
        }
        
        public WcfServiceForClientClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WcfServiceForClientClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfServiceForClientClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfServiceForClientClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void RegisterClient(string address) {
            base.Channel.RegisterClient(address);
        }
        
        public System.Threading.Tasks.Task RegisterClientAsync(string address) {
            return base.Channel.RegisterClientAsync(address);
        }
        
        public void UnRegisterClient(string address) {
            base.Channel.UnRegisterClient(address);
        }
        
        public System.Threading.Tasks.Task UnRegisterClientAsync(string address) {
            return base.Channel.UnRegisterClientAsync(address);
        }
        
        public bool CheckRtuConnection(Dto.CheckRtuConnectionDto rtuAddress) {
            return base.Channel.CheckRtuConnection(rtuAddress);
        }
        
        public System.Threading.Tasks.Task<bool> CheckRtuConnectionAsync(Dto.CheckRtuConnectionDto rtuAddress) {
            return base.Channel.CheckRtuConnectionAsync(rtuAddress);
        }
        
        public bool InitializeRtu(Dto.InitializeRtuDto rtu) {
            return base.Channel.InitializeRtu(rtu);
        }
        
        public System.Threading.Tasks.Task<bool> InitializeRtuAsync(Dto.InitializeRtuDto rtu) {
            return base.Channel.InitializeRtuAsync(rtu);
        }
        
        public bool StartMonitoring(string rtuAddress) {
            return base.Channel.StartMonitoring(rtuAddress);
        }
        
        public System.Threading.Tasks.Task<bool> StartMonitoringAsync(string rtuAddress) {
            return base.Channel.StartMonitoringAsync(rtuAddress);
        }
        
        public bool StopMonitoring(string rtuAddress) {
            return base.Channel.StopMonitoring(rtuAddress);
        }
        
        public System.Threading.Tasks.Task<bool> StopMonitoringAsync(string rtuAddress) {
            return base.Channel.StopMonitoringAsync(rtuAddress);
        }
        
        public bool ApplyMonitoringSettings(Dto.ApplyMonitoringSettingsDto settings) {
            return base.Channel.ApplyMonitoringSettings(settings);
        }
        
        public System.Threading.Tasks.Task<bool> ApplyMonitoringSettingsAsync(Dto.ApplyMonitoringSettingsDto settings) {
            return base.Channel.ApplyMonitoringSettingsAsync(settings);
        }
        
        public bool AssignBaseRef(Dto.AssignBaseRefDto baseRef) {
            return base.Channel.AssignBaseRef(baseRef);
        }
        
        public System.Threading.Tasks.Task<bool> AssignBaseRefAsync(Dto.AssignBaseRefDto baseRef) {
            return base.Channel.AssignBaseRefAsync(baseRef);
        }
    }
}
