//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataCenterCore.ClientWcfServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClientWcfServiceReference.IClientWcfService")]
    public interface IClientWcfService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientWcfService/ConfirmRtuInitialized", ReplyAction="http://tempuri.org/IClientWcfService/ConfirmRtuInitializedResponse")]
        void ConfirmRtuInitialized(Dto.RtuInitialized rtu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientWcfService/ConfirmMonitoringStarted", ReplyAction="http://tempuri.org/IClientWcfService/ConfirmMonitoringStartedResponse")]
        void ConfirmMonitoringStarted(Dto.MonitoringStarted confirm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientWcfService/ConfirmMonitoringStopped", ReplyAction="http://tempuri.org/IClientWcfService/ConfirmMonitoringStoppedResponse")]
        void ConfirmMonitoringStopped(Dto.MonitoringStopped confirm);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClientWcfServiceChannel : DataCenterCore.ClientWcfServiceReference.IClientWcfService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClientWcfServiceClient : System.ServiceModel.ClientBase<DataCenterCore.ClientWcfServiceReference.IClientWcfService>, DataCenterCore.ClientWcfServiceReference.IClientWcfService {
        
        public ClientWcfServiceClient() {
        }
        
        public ClientWcfServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClientWcfServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientWcfServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientWcfServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void ConfirmRtuInitialized(Dto.RtuInitialized rtu) {
            base.Channel.ConfirmRtuInitialized(rtu);
        }
        
        public void ConfirmMonitoringStarted(Dto.MonitoringStarted confirm) {
            base.Channel.ConfirmMonitoringStarted(confirm);
        }
        
        public void ConfirmMonitoringStopped(Dto.MonitoringStopped confirm) {
            base.Channel.ConfirmMonitoringStopped(confirm);
        }
    }
}
