namespace Iit.Fibertest.UtilsLib
{
    public enum IniSection
    {
        General,
        Server,
        RtuManager,
        DirectCharonLibrary,
        ServerMainAddress,
        ServerReserveAddress,
        ClientLocalAddress,
        Charon,
        Monitoring,
        Recovering,
        Watchdog,
        NetTcpBinding,
        MySql,
        Broadcast,
        Smtp,
        Snmp,
        SnmpListener,
        Map,
        Miscellaneous,
        WebApi,
        Migrator,
        LoadTesting,
        Uninstall,
        OtdrParameters,
        RtuEmulator,
    }
}